"""
JKJ AI Trader
Intraday Option Contract Mapper V2

Purpose:
Map logical NIFTY option candidates to actual broker contract records.

This module does NOT:
- place orders
- fetch live prices
- make BUY/SELL decisions
- modify main.py
"""


def map_nifty_option_contracts(
    candidates,
    instrument_records,
):
    """
    Map logical option candidates to actual NFO contract records.

    Parameters
    ----------
    candidates : list
        Logical option candidates generated by the Option Universe Engine.

    instrument_records : list
        Broker instrument records.

    Returns
    -------
    dict
        Mapping result with matched contracts and unmatched candidates.
    """

    if not isinstance(candidates, list):
        return {
            "Status": "INVALID",
            "Matched Contracts": [],
            "Unmatched Candidates": [],
            "Reasons": ["Candidates must be a list."],
        }

    if not isinstance(instrument_records, list):
        return {
            "Status": "INVALID",
            "Matched Contracts": [],
            "Unmatched Candidates": [],
            "Reasons": ["Instrument records must be a list."],
        }

    matched_contracts = []
    unmatched_candidates = []

    for candidate in candidates:

        if not isinstance(candidate, dict):
            unmatched_candidates.append(candidate)
            continue

        underlying = candidate.get("Underlying")
        expiry = candidate.get("Expiry")
        strike = candidate.get("Strike")
        option_type = candidate.get("Option Type")

        if (
            underlying is None
            or expiry is None
            or strike is None
            or option_type is None
        ):
            unmatched_candidates.append(candidate)
            continue

        found = False

        for instrument in instrument_records:

            if not isinstance(instrument, dict):
                continue

            instrument_name = instrument.get("name")
            instrument_expiry = instrument.get("expiry")
            instrument_strike = instrument.get("strike")
            instrument_type = instrument.get("instrument_type")

            if (
                instrument_name == underlying
                and str(instrument_expiry) == str(expiry)
                and float(instrument_strike) == float(strike)
                and instrument_type == option_type
            ):

                matched_contracts.append(
                    {
                        "Underlying": underlying,
                        "Expiry": expiry,
                        "Strike": strike,
                        "Option Type": option_type,
                        "Trading Symbol": instrument.get(
                            "tradingsymbol"
                        ),
                        "Instrument Token": instrument.get(
                            "instrument_token"
                        ),
                        "Lot Size": instrument.get(
                            "lot_size"
                        ),
                        "Exchange": instrument.get(
                            "exchange"
                        ),
                    }
                )

                found = True
                break

        if not found:
            unmatched_candidates.append(candidate)

    if len(matched_contracts) == 0:
        status = "NO MATCH"
    elif len(unmatched_candidates) == 0:
        status = "READY"
    else:
        status = "PARTIAL MATCH"

    return {
        "Status": status,
        "Matched Contracts": matched_contracts,
        "Unmatched Candidates": unmatched_candidates,
        "Matched Count": len(matched_contracts),
        "Unmatched Count": len(unmatched_candidates),
        "Reasons": [
            "Logical option candidates mapped against supplied instrument records."
        ],
    }